version: 2.1

orbs:
  nodejs: canterberry/nodejs@12.1.0

workflows:
  default:
    jobs:
    - nodejs/initialize
    - nodejs/install:
        requires:
        - nodejs/initialize
    - nodejs/style:
        requires:
        - nodejs/install
    - nodejs/build:
        requires:
        - nodejs/install
    - nodejs/test:
        requires:
        - nodejs/install
